fieldLayouts:
  2a94f0a0-f313-4ec1-97f7-c7da258786dd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0ce42f51-e53c-4a8c-bc88-1f7911c037f9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cadde915-c6fb-46a6-a77a-6fafdcb4e322 # Page Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 08e3de76-9a7f-460a-bad3-82c8118be69e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 399bee4f-19bf-4cf7-83dc-5acc8aeeb3b9
        userCondition: null
handle: contact
hasTitleField: false
name: Contact
section: c21e6094-c48b-4da7-b900-dd593e0d4125 # Contact
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
