defaultPlacement: end
enableVersioning: true
handle: events
name: Events
propagationMethod: all
siteSettings:
  402b359e-759c-4938-b279-b9a22b2c6d6a: # Waterloo Innovation Park
    enabledByDefault: true
    hasUrls: true
    template: _pages/interior_events.twig
    uriFormat: events
type: single
